### ISSUE TITLE
segment_long_utterances.sh crashes with silent audio files and non-empty transcript

### ISSUE THREAD

**Issue by christophfeinauer** [kaldi-asr/kaldi#1991]
On 32310017859cea31f167c70b7926fadde0761c36

MWE with `silence.wav` an audio file with silence of non-zero length:

```
. ./cmd.sh
. ./path.sh

dict_dir=data/local/dict
mfccdir=`pwd`/mfcc
set -e
stage=1
nj_train=1

if [ -d data/train ]; then
    rm -rf data/train
fi
mkdir -p data/train
echo "anonymous-20100108-vhh_de11-092 alles ist gepflegt und jederzeit einsatzbereiti" > data/train/text
echo "Manu-20140327-m41_deM41-56 er würde kommen und ihr sagen was sie tun müsste" >> data/train/text
echo "anonymous-20100108-vhh_de11-092 anonymous" > data/train/utt2spk
echo "Manu-20140327-m41_deM41-56 Manu" >> data/train/utt2spk
echo "anonymous-20100108-vhh_de11-092 data/silence.wav" > data/train/wav.scp
echo "Manu-20140327-m41_deM41-56 data/nonsilence.wav" >> data/train/wav.scp

utils/fix_data_dir.sh data/train
steps/make_mfcc.sh --nj 1 --cmd "$train_cmd" data/train exp/make_mfcc/train mfcc
steps/compute_cmvn_stats.sh data/train exp/make_mfcc/train mfcc

if [ $stage -le 1 ]; then
    mkdir -p local/temp
    for data_set in train; do
        steps/cleanup/segment_long_utterances.sh --nj $nj_train --cmd "$train_cmd" \
        exp/tri5a data/lang data/${data_set} data/${data_set}_seg local/temp
    done
    rm -rf local/temp
fi
```

crashes with 

```
2017-11-01 14:07:51,096 [steps/cleanup/internal/resolve_ctm_edits_overlaps.py:72 - read_segments - INFO ] Read 2 lines from segments file local/temp/train_uniform_seg/segments
2017-11-01 14:07:51,096 [steps/cleanup/internal/resolve_ctm_edits_overlaps.py:120 - read_ctm_edits - INFO ] Read 12 lines from CTM local/temp/lats/score_10/ctm_edits
2017-11-01 14:07:51,096 [steps/cleanup/internal/resolve_ctm_edits_overlaps.py:314 - run - ERROR ] Failed to process CTM edits for recording anonymous-20100108-vhh_de11-092
2017-11-01 14:07:51,097 [steps/cleanup/internal/resolve_ctm_edits_overlaps.py:326 - main - ERROR ] Failed to resolve overlaps
Traceback (most recent call last):
  File "steps/cleanup/internal/resolve_ctm_edits_overlaps.py", line 324, in main
    run(args)
  File "steps/cleanup/internal/resolve_ctm_edits_overlaps.py", line 310, in run
    ctm_edits_for_reco = resolve_overlaps(ctm_edits_for_reco, segments)
  File "steps/cleanup/internal/resolve_ctm_edits_overlaps.py", line 179, in resolve_overlaps
    raise RuntimeError('CTMs for recording is empty. '
RuntimeError: CTMs for recording is empty. Something wrong with the input ctms
Traceback (most recent call last):
  File "steps/cleanup/internal/resolve_ctm_edits_overlaps.py", line 342, in <module>
    main()
  File "steps/cleanup/internal/resolve_ctm_edits_overlaps.py", line 327, in main
    raise RuntimeError
RuntimeError
```

I think the problem is that `smith_waterman_alignment` in `steps/cleanup/internal/align_ctm_ref.py` returns an empty output for that utterance and `local/temp/lats/score_10/train_uniform_seg.ctm_edits.1` does not contain edits for it, as the error message says.

Wouldn't a warning be enough here?

**Comment by danpovey** [comment]
@vimalmanohar, can you please address this?

**Comment by danpovey** [comment]
Can you please see if PR  #1993 addresses the problem?

**Comment by christophfeinauer** [comment]
Yes it does

**Comment by danpovey** [comment]
Resolved in #1993

**Comment by christophfeinauer** [comment]
Sorry to bother you again but there is a bug in the bugfix that doesn't crash but leads to incomplete results:
In `run` in `resolve_ctm_overlaps`:
```
....
for reco, utts in reco2utt.iteritems():
        ctm_edits_for_reco = []
        for utt in sorted(utts, key=lambda x: segments[x][1]):
            if (reco, utt) in ctm_edits:
                ctm_edits_for_reco.append(ctm_edits[(reco, utt)])
        try:
            if len(ctm_edits_for_reco) == 0:
                logger.warn('CTMs for recording %s is empty.',
                             reco)
                break   # Go to the next recording
.....
```
the `break` doesn't go to the next recording but exits the `for reco` loop. This doesn't raise an exception but not all utterances are processed. The `break` should be a `continue`.

**Comment by vimalmanohar** [comment]
@christophfeinauer Yes, it should be continue. Please add the change to your other PR.
