### ISSUE TITLE
steps/cleanup/internal/modify_ctm_edits.py division by zero

### ISSUE THREAD

**Issue by christophfeinauer** [kaldi-asr/kaldi#1994]
In `steps/cleanup/internal/modify_ctm_edits.py` in the function `PrintNonScoredStats` the following code doesn't check if `num_incorrect_lines` is >0:

```
num_incorrect_lines = num_lines - num_correct_lines
percent_lines_incorrect= '%.2f' % (num_incorrect_lines * 100.0 / num_lines)
percent_modified = '%.2f' % (num_lines_modified * 100.0 / num_lines);
percent_of_incorrect_modified = '%.2f' % (num_lines_modified * 100.0 / num_incorrect_lines)
```
this results in `modify_ctm_edits.log`:

```
# steps/cleanup/internal/modify_ctm_edits.py --verbose=3 local/temp/non_scored_words.txt local/temp/ctm_edits local/temp/ctm_edits.modified 
# Started at Thu Nov  2 10:09:33 UTC 2017
#
Traceback (most recent call last):
  File "steps/cleanup/internal/modify_ctm_edits.py", line 439, in <module>
    PrintNonScoredStats()
  File "steps/cleanup/internal/modify_ctm_edits.py", line 376, in PrintNonScoredStats
    percent_of_incorrect_modified = '%.2f' % (num_lines_modified * 100.0 / num_incorrect_lines)
ZeroDivisionError: float division by zero
# Accounting: time=0 threads=1
# Ended (code 1) at Thu Nov  2 10:09:33 UTC 2017, elapsed time 0 seconds
```

I think `PrintRepetitionStats` in the same file has the same problem.

**Comment by danpovey** [comment]
Hm.  Maybe you could make a PR for a fix?

On Thu, Nov 2, 2017 at 7:15 AM, Christoph Feinauer <notifications@github.com

**Comment by christophfeinauer** [comment]
Hi, sure I will do it hopefully today
