### ISSUE TITLE
RNNLM script change from utf-8 to latin-1

### ISSUE THREAD

**Issue by wsycysdrhpa** [kaldi-asr/kaldi#2595]
RNNLM script coding has change from utf-8 to latin-1, that means do not support chinese?

**Comment by wsycysdrhpa** [comment]
It may encounter some problems when just run ptb.
rnnlm/get_unigram_probs.py: bad data-weights line: 'ptb   1   1.0':

**Comment by danpovey** [comment]
No, latin-1 means read as bytes and don't try to decode.
Please give more context (e.g. larger screen paste for that error).
@hainan-xv, please try to figure out what went wrong.

**Comment by wsycysdrhpa** [comment]
The more INFOs just like that.

*** Downloading PTB text data ***
2018-08-07 09:39:56 URL:https://raw.githubusercontent.com/townie/PTB-dataset-from-Tomas-Mikolov-s-webpage/master/data//ptb.train.txt [5101618/5101618] -> "ptb.train.txt" [1]
2018-08-07 09:39:57 URL:https://raw.githubusercontent.com/townie/PTB-dataset-from-Tomas-Mikolov-s-webpage/master/data//ptb.valid.txt [399782/399782] -> "ptb.valid.txt" [1]
2018-08-07 09:39:58 URL:https://raw.githubusercontent.com/townie/PTB-dataset-from-Tomas-Mikolov-s-webpage/master/data//ptb.test.txt [449945/449945] -> "ptb.test.txt" [1]
*** Finished downloading PTB text data ***
rnnlm/ensure_counts_present.sh: generating counts file for data/text/dev.txt
rnnlm/ensure_counts_present.sh: generating counts file for data/text/ptb.txt
rnnlm/get_vocab.py: vocab is generated with 10003 words.
rnnlm/get_unigram_probs.py: bad data-weights line: 'ptb   1   1.0':

**Comment by wsycysdrhpa** [comment]
And if i change it to utf-8, it can go further, but shows Other errors after.

**Comment by wsycysdrhpa** [comment]
5.3 version is ok.

**Comment by danpovey** [comment]
I was able to replicate your problem-- not sure why this started happening only now.  The fix in #2597 seems to resolve it, can you please test?

**Comment by wsycysdrhpa** [comment]
I have tried, it seems skip the error, but the infos show as follows.

*** Downloading PTB text data ***
2018-08-07 10:22:43 URL:https://raw.githubusercontent.com/townie/PTB-dataset-from-Tomas-Mikolov-s-webpage/master/data//ptb.train.txt [5101618/5101618] -> "ptb.train.txt" [1]
2018-08-07 10:22:44 URL:https://raw.githubusercontent.com/townie/PTB-dataset-from-Tomas-Mikolov-s-webpage/master/data//ptb.valid.txt [399782/399782] -> "ptb.valid.txt" [1]
2018-08-07 10:22:45 URL:https://raw.githubusercontent.com/townie/PTB-dataset-from-Tomas-Mikolov-s-webpage/master/data//ptb.test.txt [449945/449945] -> "ptb.test.txt" [1]
*** Finished downloading PTB text data ***
rnnlm/ensure_counts_present.sh: generating counts file for data/text/dev.txt
rnnlm/ensure_counts_present.sh: generating counts file for data/text/ptb.txt
rnnlm/get_vocab.py: vocab is generated with 10003 words.
rnnlm/get_unigram_probs.py: generated unigram probs.
rnnlm/choose_features.py: chose 7283 features.
rnnlm/get_unigram_probs.py: generated unigram probs.
rnnlm/validate_config_dir.sh: validated config dir exp/rnnlm_tdnn_a/config
rnnlm/prepare_rnnlm_dir.sh: validating input
rnnlm/get_unigram_probs.py: generated unigram probs.
rnnlm/validate_config_dir.sh: validated config dir exp/rnnlm_tdnn_a/config
rnnlm/get_unigram_probs.py: generated unigram probs.
rnnlm/get_word_features.py: made features for 10003 words.
rnnlm/prepare_rnnlm_dir.sh: preparing split-up integerized text data with weights
get_num_splits.sh: based on tot-words=929589 (with multiplicities: 929589) and target-words-per-split=5000000, got 1 splits, actual words-per-split is 929589
 ... and num-repeats is 5
rnnlm/prepare_split_data.py: distributing data to temporary files
rnnlm/prepare_split_data.py: converting from text to integer form.
rnnlm/prepare_split_data.py: converting dev data from text to integer form.
rnnlm/prepare_split_data.py: created split data in exp/rnnlm_tdnn_a/text
rnnlm/prepare_rnnlm_dir.sh: initializing neural net
steps/nnet3/xconfig_to_configs.py --xconfig-file=exp/rnnlm_tdnn_a/config/xconfig --config-dir=exp/rnnlm_tdnn_a/config/nnet
ERROR:root:***Exception caught while parsing the following xconfig line:
*** relu-renorm-layer name=tdnn1 dim=400 input=Append(0, IfDefined(-1))

Traceback (most recent call last):
  File "steps/nnet3/xconfig_to_configs.py", line 333, in <module>
    main()
  File "steps/nnet3/xconfig_to_configs.py", line 323, in main
    all_layers = xparser.read_xconfig_file(args.xconfig_file, existing_layers)
  File "steps/libs/nnet3/xconfig/parser.py", line 186, in read_xconfig_file
    this_layer = xconfig_line_to_object(line, existing_layers)
  File "steps/libs/nnet3/xconfig/parser.py", line 93, in xconfig_line_to_object
    return config_to_layer[first_token](first_token, key_to_value, prev_layers)
  File "steps/libs/nnet3/xconfig/basic_layers.py", line 706, in __init__
    XconfigLayerBase.__init__(self, first_token, key_to_value, prev_names)
  File "steps/libs/nnet3/xconfig/basic_layers.py", line 75, in __init__
    self.check_configs()
  File "steps/libs/nnet3/xconfig/basic_layers.py", line 751, in check_configs
    if self.config['learning-rate-factor'] <= 0.0:
TypeError: '<=' not supported between instances of 'str' and 'float'

**Comment by danpovey** [comment]
OK, pull that branch and try again.
I suspect you are hitting a python3 compatibility issue because that
doesn't barf in python2.

**Comment by wsycysdrhpa** [comment]
Yeah! It works now, thank you!
But i still be inquisitive about kaldi prefer python2 or 3, thanks.

**Comment by misbullah** [comment]
I also get this error last time: rnnlm/get_unigram_probs.py: bad data-weights line: 'ptb 1 1.0':

I change spaces with tab and it works.

Just for sharing.
