### ISSUE TITLE
ImportError: _pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow20UnaryDatasetOpKernel11MakeDatasetEPNS_15OpKernelContextEPPNS_11DatasetBaseE

### ISSUE THREAD

**Issue by jianxucsm** [kaldi-asr/kaldi#2731]
Hi There:

I am on ubuntu 18.04. use conda environment to run python and tensorflow.

the stuff works fine before and today during the pycharm debugging, the next run pops up the 

ImportError: /home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow20UnaryDatasetOpKernel11MakeDatasetEPNS_15OpKernelContextEPPNS_11DatasetBaseE

tried to remove the conda environment and recreate a new conda environment
install the tensorflow via pip install tensorflow==1.10.0 and 1.10.1
none of them works.

after installation, run python. the python is version 

Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux

try to import tensorflow as tf

get following error message:

Traceback (most recent call last):
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow20UnaryDatasetOpKernel11MakeDatasetEPNS_15OpKernelContextEPPNS_11DatasetBaseE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/jxu/anaconda3/envs/tf-cpu/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow20UnaryDatasetOpKernel11MakeDatasetEPNS_15OpKernelContextEPPNS_11DatasetBaseE

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

please kindly help to suggest to fix the problem. 

this happens suddenly on my computer. it was working perfectly.

Regards,

Jian Xu

**Comment by danpovey** [comment]
Did you mean to submit this somewhere else?

**Comment by jianxucsm** [comment]
sorry want to submit under tensorflow
