### ISSUE TITLE
install irstlm error: automake failed

### ISSUE THREAD

**Issue by zdgithub** [kaldi-asr/kaldi#2973]
When I tried to install  irstlm to run the timit recipe, the error occurred:
```
****() Installing IRSTLM
Cloning into 'irstlm'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 1781 (delta 3), reused 0 (delta 0), pack-reused 1771
Receiving objects: 100% (1781/1781), 3.54 MiB | 597.00 KiB/s, done.
Resolving deltas: 100% (1184/1184), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "/home/zhanghao/anaconda3/bin/automake", line 7, in <module>
    from automake.cli import cli
  File "/home/zhanghao/anaconda3/lib/python3.7/site-packages/automake/cli.py", line 6, in <module>
    from utils import printmsg
ModuleNotFoundError: No module named 'utils'
patching file configure.ac
patching file src/Makefile.am
Calling /home/zhanghao/anaconda3/bin/autoreconf
configure.ac:10: warning: LT_INIT was called before AM_PROG_AR
/usr/share/aclocal-1.15/ar-lib.m4:13: AM_PROG_AR is expanded from...
configure.ac:10: the top level
configure.ac:10: warning: AC_PROG_LIBTOOL was called before AM_PROG_AR
/usr/share/aclocal-1.15/ar-lib.m4:13: AM_PROG_AR is expanded from...
configure.ac:10: the top level
configure.ac:10: warning: LT_INIT was called before AM_PROG_AR
/usr/share/aclocal-1.15/ar-lib.m4:13: AM_PROG_AR is expanded from...
configure.ac:10: the top level
configure.ac:10: warning: AC_PROG_LIBTOOL was called before AM_PROG_AR
/usr/share/aclocal-1.15/ar-lib.m4:13: AM_PROG_AR is expanded from...
configure.ac:10: the top level
configure.ac:10: warning: LT_INIT was called before AM_PROG_AR
aclocal.m4:9118: AM_PROG_AR is expanded from...
configure.ac:10: the top level
configure.ac:10: warning: AC_PROG_LIBTOOL was called before AM_PROG_AR
aclocal.m4:9118: AM_PROG_AR is expanded from...
configure.ac:10: the top level
configure.ac:10: warning: LT_INIT was called before AM_PROG_AR
aclocal.m4:9118: AM_PROG_AR is expanded from...
configure.ac:10: the top level
configure.ac:10: warning: AC_PROG_LIBTOOL was called before AM_PROG_AR
aclocal.m4:9118: AM_PROG_AR is expanded from...
configure.ac:10: the top level
configure.ac:10: warning: LT_INIT was called before AM_PROG_AR
aclocal.m4:9118: AM_PROG_AR is expanded from...
configure.ac:10: the top level
configure.ac:10: warning: AC_PROG_LIBTOOL was called before AM_PROG_AR
aclocal.m4:9118: AM_PROG_AR is expanded from...
configure.ac:10: the top level
Traceback (most recent call last):
  File "/home/zhanghao/anaconda3/bin/automake", line 7, in <module>
    from automake.cli import cli
  File "/home/zhanghao/anaconda3/lib/python3.7/site-packages/automake/cli.py", line 6, in <module>
    from utils import printmsg
ModuleNotFoundError: No module named 'utils'
autoreconf: automake failed with exit status: 1
autoreconf FAILED
trying '/home/zhanghao/anaconda3/bin/libtoolize --force; /home/zhanghao/anaconda3/bin/automake --add-missing ; /home/zhanghao/anaconda3/bin/autoreconf'
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
...
...
Traceback (most recent call last):
  File "/home/zhanghao/anaconda3/bin/automake", line 7, in <module>
    from automake.cli import cli
  File "/home/zhanghao/anaconda3/lib/python3.7/site-packages/automake/cli.py", line 6, in <module>
    from utils import printmsg
ModuleNotFoundError: No module named 'utils'
autoreconf: automake failed with exit status: 1
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
***() Error compiling IRSTLM. The error messages could help you 
***() in figuring what went wrong.

```

**Comment by danpovey** [comment]
Looks like you need to a little cleanup on your path.  Your automake is in `/home/zhanghao/anaconda3/bin/automake`
.. you should use the system one.  In any case it would be an anaconda problem, not a Kaldi problem.

**Comment by zdgithub** [comment]
Thanks for your quick reply. I will have a try.
