### ISSUE TITLE
"Please add ProcessScaleDescriptor method"

### ISSUE THREAD

**Issue by luckmoon** [kaldi-asr/kaldi#3475]
When I run command 
`steps/nnet3/nnet3_to_dot.sh exp/chain/tdnn1i_sp/final.mdl /tmp/1.dot /tmp/2.pdf`
in egs/mini_librispeech/s5 directory, return below msg:

steps/nnet3/nnet3_to_dot.sh exp/chain/tdnn1i_sp/final.mdl /tmp/1.dot /tmp/2.pdf
steps/nnet3/dot/nnet3_to_dot.py --component-attributes name,type /tmp/1.dot
nnet3-am-info exp/chain/tdnn1i_sp/final.mdl
Traceback (most recent call last):
  File "steps/nnet3/dot/nnet3_to_dot.py", line 467, in <module>
    dot_graph = ParseConfigLines(lines, component_attributes = component_attributes, node_prefixes = node_prefixes)
  File "steps/nnet3/dot/nnet3_to_dot.py", line 426, in ParseConfigLines
    dot_graph += Nnet3ComponentNodeToDot(parsed_config)
  File "steps/nnet3/dot/nnet3_to_dot.py", line 366, in Nnet3ComponentNodeToDot
    dot_graph += Nnet3DescriptorToDot(parsed_config['input'], parsed_config['name'])
  File "steps/nnet3/dot/nnet3_to_dot.py", line 281, in Nnet3DescriptorToDot
    dot_lines += DescriptorSegmentToDot(segment, parent_node_name, parent_node_name)
  File "steps/nnet3/dot/nnet3_to_dot.py", line 265, in DescriptorSegmentToDot
    dot_graph += ProcessSumDescriptor(segment, parent_node_name, affix, edge_attributes)
  File "steps/nnet3/dot/nnet3_to_dot.py", line 192, in ProcessSumDescriptor
    dot_graph += DescriptorSegmentToDot(sub_segment, "{0}:{1}".format(desc_name, part_name), "{0}_{1}".format(desc_name, i))
  File "steps/nnet3/dot/nnet3_to_dot.py", line 273, in DescriptorSegmentToDot
    raise Exception('Descriptor {0}, is not recognized by this script. Please add Process{0}Descriptor method'.format(segment['name']))
Exception: Descriptor Scale, is not recognized by this script. Please add ProcessScaleDescriptor method

I think maybe it is a bug to be fixed.

**Comment by danpovey** [comment]
Yes, it is a bug, but that tool is not very actively developed.  If you have time to commit a fix, go ahead.
