### ISSUE TITLE
Bug in read_matrix_ascii function in steps/libs/common.py

### ISSUE THREAD

**Issue by LuckyMO285** [kaldi-asr/kaldi#4605]
After upgrading the system from Ubuntu 18.04 to Ubuntu 20.04, I encountered an error when calling the read_matrix_ascii function:
```
2021-08-02 20:57:43,248 [local/vad_files/merge_segment_targets_to_recording.py:191 - run - ERROR ] Command 'copy-feats --binary=false /home/d2-1/4TB/kaldi-master/egs/VAD/work_area/exp/segmentation_1a/tri4a_train_100k_sup_targets/targets.1.ark:70 -' failed
Traceback (most recent call last):
  File "local/vad_files/merge_segment_targets_to_recording.py", line 295, in <module>
    main()
  File "local/vad_files/merge_segment_targets_to_recording.py", line 289, in main
    run(args)
  File "local/vad_files/merge_segment_targets_to_recording.py", line 188, in run
    mat = np.matrix(common_lib.read_matrix_ascii(p.stdout),
  File "/home/d2-1/4TB/kaldi-master/egs/VAD/work_area/steps/libs/common.py", line 384, in read_matrix_ascii
    raise RuntimeError
RuntimeError
```
The problem was solved by changing lines 
```
1. if first != b' [': ---------> 1. if first != b' [' and first != ' [':
2. if arr[-1] != ']': ---------> 2. if arr[-1] != b']' and arr[-1] != ']':
```

**Comment by danpovey** [comment]
OK.  Your fix is maybe not 100% the right thing to do here, but fully debugging these encoding issues is very hard so I'm just using your fix.  I'll wait for someone else to merge.
