### ISSUE TITLE
wenetspeech get_egs error

### ISSUE THREAD

**Issue by shushanxingzhe** [kaldi-asr/kaldi#4724]
@LvHang 每次我训练到get_egs快结束时都会遇到下面的错误，但是我却没法通过shuffle.*.log看出具体原因，希望您能指点一下我该怎么做。

```
steps/nnet3/chain/get_egs.sh: recombining and shuffling order of archives on disk
run.pl: 16 / 400 failed, log is in exp/train_l/chain_cleaned/cnn_tdnn_1c_sp/egs/log/shuffle.*.log
Traceback (most recent call last):
  File "steps/nnet3/chain/train.py", line 644, in main
    train(args, run_opts)
  File "steps/nnet3/chain/train.py", line 405, in train
    stage=args.egs_stage)
  File "steps/libs/nnet3/train/chain_objf/acoustic_model.py", line 118, in generate_chain_egs
    egs_opts=egs_opts if egs_opts is not None else ''))
  File "steps/libs/common.py", line 129, in execute_command
    p.returncode, command))
Exception: Command exited with status 1: steps/nnet3/chain/get_egs.sh --frames-overlap-per-eg 0                 --cmd "run.pl --mem 10G --config conf/queue_no_k20.conf"                 --cmvn-opts "--norm-means=false --norm-vars=false"                 --online-ivector-dir "exp/train_l/nnet3_cleaned/ivectors_train_l_sp_hires"                 --left-context 85                 --right-context 58                 --left-context-initial -1                 --right-context-final -1                 --left-tolerance '5'                 --right-tolerance '5'                 --frame-subsampling-factor 3                 --alignment-subsampling-factor 3                 --stage -10                 --frames-per-iter 3000000                 --frames-per-eg 150,110,100                 --srand 0                 data/train_l_sp_hires exp/train_l/chain_cleaned/cnn_tdnn_1c_sp exp/train_l/chain_cleaned/tri3b_train_l_sp_lats exp/train_l/chain_cleaned/cnn_tdnn_1c_sp/egs
steps/nnet3/chain/train.py --stage=-3 --cmd=run.pl --mem 5G --config conf/queue_no_k20.conf --feat.online-ivector-dir=exp/train_l/nnet3_cleaned/ivectors_train_l_sp_hires --feat.cmvn-opts=--norm-means=false --norm-vars=false --chain.xent-regularize 0.1 --chain.leaky-hmm-coefficient=0.1 --chain.l2-regularize=0.0 --chain.apply-deriv-weights=false --chain.lm-opts=--num-extra-lm-states=2000 --trainer.add-option=--optimization.memory-compression-level=2 --trainer.srand=0 --trainer.max-param-change=2.0 --trainer.num-epochs=4 --trainer.frames-per-iter=3000000 --trainer.optimization.num-jobs-initial=8 --trainer.optimization.num-jobs-final=8 --trainer.optimization.initial-effective-lrate=0.00015 --trainer.optimization.final-effective-lrate=0.000015 --trainer.num-chunk-per-minibatch=128,64 --egs.chunk-width=150,110,100 --egs.dir= --egs.opts=--frames-overlap-per-eg 0 --egs.stage=-10 --egs.cmd=run.pl --mem 10G --config conf/queue_no_k20.conf --cleanup.remove-egs=false --use-gpu=true --reporting.email= --feat-dir=data/train_l_sp_hires --tree-dir=exp/train_l/chain_cleaned/tree_sp --lat-dir=exp/train_l/chain_cleaned/tri3b_train_l_sp_lats --dir=exp/train_l/chain_cleaned/cnn_tdnn_1c_sp
['steps/nnet3/chain/train.py', '--stage=-3', '--cmd=run.pl --mem 5G --config conf/queue_no_k20.conf', '--feat.online-ivector-dir=exp/train_l/nnet3_cleaned/ivectors_train_l_sp_hires', '--feat.cmvn-opts=--norm-means=false --norm-vars=false', '--chain.xent-regularize', '0.1', '--chain.leaky-hmm-coefficient=0.1', '--chain.l2-regularize=0.0', '--chain.apply-deriv-weights=false', '--chain.lm-opts=--num-extra-lm-states=2000', '--trainer.add-option=--optimization.memory-compression-level=2', '--trainer.srand=0', '--trainer.max-param-change=2.0', '--trainer.num-epochs=4', '--trainer.frames-per-iter=3000000', '--trainer.optimization.num-jobs-initial=8', '--trainer.optimization.num-jobs-final=8', '--trainer.optimization.initial-effective-lrate=0.00015', '--trainer.optimization.final-effective-lrate=0.000015', '--trainer.num-chunk-per-minibatch=128,64', '--egs.chunk-width=150,110,100', '--egs.dir=', '--egs.opts=--frames-overlap-per-eg 0', '--egs.stage=-10', '--egs.cmd=run.pl --mem 10G --config conf/queue_no_k20.conf', '--cleanup.remove-egs=false', '--use-gpu=true', '--reporting.email=', '--feat-dir=data/train_l_sp_hires', '--tree-dir=exp/train_l/chain_cleaned/tree_sp', '--lat-dir=exp/train_l/chain_cleaned/tri3b_train_l_sp_lats', '--dir=exp/train_l/chain_cleaned/cnn_tdnn_1c_sp']
"nohup.out" 2584L, 173792C   
```

**Comment by shushanxingzhe** [comment]
I can see the input files cegs_orig.*.15.ark not empty, but the output files is empty. I can't figure out what had cause that. Even I rerun get_egs.sh again, I still get the same error. Please give me some advice, what should I do. Thanks in advance!
```

(base) [root@oracledb 二 4月 12 09:26:19 cnn_tdnn_1c_sp]# find egs -name cegs_orig.*.15.ark -exec ls -lh {} \;
-rw-r--r-- 1 root root 34M 4月  10 14:41 egs/cegs_orig.13.15.ark
-rw-r--r-- 1 root root 28M 4月  10 12:43 egs/cegs_orig.11.15.ark
-rw-r--r-- 1 root root 45M 4月  10 16:18 egs/cegs_orig.3.15.ark
-rw-r--r-- 1 root root 29M 4月  10 13:23 egs/cegs_orig.12.15.ark
-rw-r--r-- 1 root root 35M 4月  10 14:37 egs/cegs_orig.8.15.ark
-rw-r--r-- 1 root root 41M 4月  10 14:23 egs/cegs_orig.1.15.ark
-rw-r--r-- 1 root root 34M 4月  10 14:20 egs/cegs_orig.10.15.ark
-rw-r--r-- 1 root root 36M 4月  10 13:46 egs/cegs_orig.14.15.ark
-rw-r--r-- 1 root root 33M 4月  10 14:32 egs/cegs_orig.9.15.ark
-rw-r--r-- 1 root root 36M 4月  10 14:21 egs/cegs_orig.2.15.ark
-rw-r--r-- 1 root root 34M 4月  10 14:52 egs/cegs_orig.5.15.ark
-rw-r--r-- 1 root root 30M 4月  10 13:55 egs/cegs_orig.6.15.ark
-rw-r--r-- 1 root root 39M 4月  10 15:24 egs/cegs_orig.15.15.ark
-rw-r--r-- 1 root root 37M 4月  10 15:02 egs/cegs_orig.4.15.ark
-rw-r--r-- 1 root root 39M 4月  10 15:10 egs/cegs_orig.7.15.ark
-rw-r--r-- 1 root root 32M 4月  10 18:17 egs/cegs_orig.16.15.ark
-rw-r--r-- 1 root root 26M 4月  10 17:24 egs/cegs_orig.17.15.ark
-rw-r--r-- 1 root root 27M 4月  10 17:13 egs/cegs_orig.18.15.ark
-rw-r--r-- 1 root root 34M 4月  10 18:10 egs/cegs_orig.19.15.ark
-rw-r--r-- 1 root root 31M 4月  10 18:12 egs/cegs_orig.20.15.ark
-rw-r--r-- 1 root root 27M 4月  10 17:29 egs/cegs_orig.21.15.ark
-rw-r--r-- 1 root root 43M 4月  10 20:17 egs/cegs_orig.22.15.ark
-rw-r--r-- 1 root root 62M 4月  10 22:35 egs/cegs_orig.23.15.ark
-rw-r--r-- 1 root root 52M 4月  10 22:23 egs/cegs_orig.24.15.ark
-rw-r--r-- 1 root root 57M 4月  10 22:34 egs/cegs_orig.25.15.ark
-rw-r--r-- 1 root root 63M 4月  10 22:43 egs/cegs_orig.26.15.ark
-rw-r--r-- 1 root root 61M 4月  10 22:54 egs/cegs_orig.27.15.ark
-rw-r--r-- 1 root root 59M 4月  10 22:56 egs/cegs_orig.28.15.ark
-rw-r--r-- 1 root root 70M 4月  10 23:06 egs/cegs_orig.29.15.ark
-rw-r--r-- 1 root root 56M 4月  11 00:05 egs/cegs_orig.30.15.ark
-rw-r--r-- 1 root root 55M 4月  11 01:53 egs/cegs_orig.33.15.ark
-rw-r--r-- 1 root root 67M 4月  11 01:45 egs/cegs_orig.31.15.ark
-rw-r--r-- 1 root root 50M 4月  11 01:56 egs/cegs_orig.32.15.ark
-rw-r--r-- 1 root root 59M 4月  11 01:58 egs/cegs_orig.34.15.ark
-rw-r--r-- 1 root root 58M 4月  11 01:56 egs/cegs_orig.35.15.ark
-rw-r--r-- 1 root root 57M 4月  11 01:44 egs/cegs_orig.36.15.ark
-rw-r--r-- 1 root root 64M 4月  11 04:17 egs/cegs_orig.37.15.ark
-rw-r--r-- 1 root root 61M 4月  11 05:58 egs/cegs_orig.43.15.ark
-rw-r--r-- 1 root root 58M 4月  11 06:19 egs/cegs_orig.44.15.ark
-rw-r--r-- 1 root root 65M 4月  11 06:10 egs/cegs_orig.38.15.ark
-rw-r--r-- 1 root root 61M 4月  11 06:21 egs/cegs_orig.40.15.ark
-rw-r--r-- 1 root root 66M 4月  11 06:18 egs/cegs_orig.39.15.ark
-rw-r--r-- 1 root root 64M 4月  11 06:17 egs/cegs_orig.42.15.ark
-rw-r--r-- 1 root root 59M 4月  11 06:07 egs/cegs_orig.41.15.ark
-rw-r--r-- 1 root root 66M 4月  11 06:42 egs/cegs_orig.45.15.ark
-rw-r--r-- 1 root root 59M 4月  11 07:21 egs/cegs_orig.47.15.ark
-rw-r--r-- 1 root root 60M 4月  11 07:17 egs/cegs_orig.49.15.ark
-rw-r--r-- 1 root root 51M 4月  11 07:15 egs/cegs_orig.48.15.ark
-rw-r--r-- 1 root root 59M 4月  11 07:14 egs/cegs_orig.50.15.ark
-rw-r--r-- 1 root root 60M 4月  11 07:17 egs/cegs_orig.46.15.ark
(base) [root@oracledb 二 4月 12 09:26:23 cnn_tdnn_1c_sp]# cd egs/
(base) [root@oracledb 二 4月 12 09:26:27 egs]# ll -thr cegs.15.1.ark cegs.15.2.ark cegs.15.3.ark
lrwxrwxrwx 1 root root 11 4月  11 07:21 cegs.15.1.ark -> cegs.43.ark
lrwxrwxrwx 1 root root 11 4月  11 07:21 cegs.15.2.ark -> cegs.44.ark
lrwxrwxrwx 1 root root 11 4月  11 07:21 cegs.15.3.ark -> cegs.45.ark
(base) [root@oracledb 二 4月 12 09:26:33 egs]# ll -thr cegs.43.ark cegs.44.ark cegs.45.ark
-rw-r--r-- 1 root root 0 4月  11 08:24 cegs.43.ark
-rw-r--r-- 1 root root 0 4月  11 08:24 cegs.44.ark
-rw-r--r-- 1 root root 0 4月  11 08:24 cegs.45.ark

```

**Comment by shushanxingzhe** [comment]
@LvHang Very thanks for your kindly reply. Now the problem have been solved. But now I get another problem, the log show "CUDA error: 'out of memory'"

**Comment by shushanxingzhe** [comment]
I have solve this problem by changing num-jobs-initial and num-jobs-final to a lower value.
Very thanks for your great work.

**Comment by LvHang** [comment]
For the “CUDA out of memory” problem, maybe you can tune the batch size and other hyper-parameters.
If you solve the problem by changing the num-jobs-initial and num-jobs-final, I guess you didn't limit the GPU mode to the "exclusive processing" mode.
From my experience, maybe on the Tedlium dataset, tuning the num-jobs-initial and num-jobs-final will change the performance a little bit. But I think it's OK. Anyway, good luck.
